### PR TITLE
added cross compilation

### PR DESCRIPTION
**Pull request by Peppi-Ressler**

### CODE REVIEW

**Comment by Karry** [comment]
Latest Scala 2.11 is `2.11.12` please use latest one, LGTM otherwise

@jakubjanecek is there some reason for avoid crosscompilation?

**Comment by Peppi-Ressler** [comment]
Updated to latest 2.11 version

**Comment by jakubjanecek** [comment]
For this library it's not important but in other libraries we want to use the features of Scala 2.12 so cross-compilation to 2.11 holds us back. I feel like 2.11 is very old now so I don't want to spread it even more. In this case let's cross-compile it.

**Review by jakubjanecek — APPROVED** [review]

**Comment by jakubjanecek** [comment]
@Peppi-Ressler I think you also have to update Travis configuration so that it gets built.

**Pull request closed without merging**
